issuer: https://token.actions.githubusercontent.com
# Allow get-all-docs repository to read metadata and pages info from all liatrio repos
subject_pattern: "repo:liatrio(@[0-9]+)?/get-all-docs(@[0-9]+)?:.*"

permissions:
  metadata: read
  pages: read
  contents: read
